### ISSUE TITLE
Compilation failed; can't get past initial install

### ISSUE THREAD

**Issue by alechp** [avdv/scalals#14]
![Screen Shot 2020-11-03 at 2 40 30 PM](https://user-images.githubusercontent.com/3058939/98048452-8e2c1480-1de2-11eb-8ace-25bf1506b267.png)

**Comment by avdv** [comment]
Hi.

Which Java version do you use? I am using Java 11...

**Comment by avdv** [comment]
BTW, it is probably easiest to checkout the repository with submoodules and just call the travis-install script  which is what is done on the CI.
```
git clone --recurse-submodules https://github.com/avdv/scalals.git
cd scalals
SN_BUILD=101 SBT_VERSION=1.3.13 scripts/travis-install
```

**Comment by avdv** [comment]
Oh, and is there a reason why you want to build it yourself instead of using the provided binaries?

**Comment by alechp** [comment]
> Oh, and is there a reason why you want to build it yourself instead of using the provided binaries?

How should I install a raw binary on macOS? Thought SIP protection prevented moving binaries to /usr/bin

**Comment by alechp** [comment]
> Hi.
> 
> Which Java version do you use? I am using Java 11...

![Screen Shot 2020-11-08 at 11 55 08 AM](https://user-images.githubusercontent.com/3058939/98482893-437f1380-21b9-11eb-9167-b32d6f50cbf8.png)

**Comment by alechp** [comment]
> If you want to give Nix a try, head over to nixos.org/guides/install-nix.html to install it and then run nix-shell to enter the build environment (all dependencies like Java, clang, sbt and so on pinned to a specific version for reproducible builds).

Is this a requirement for scalals to build or just an OS recommendation?

> Hi.
> 
> Which Java version do you use? I am using Java 11...

![Screen Shot 2020-11-08 at 11 55 08 AM](https://user-images.githubusercontent.com/3058939/98482893-437f1380-21b9-11eb-9167-b32d6f50cbf8.png)

> Oh, and is there a reason why you want to build it yourself instead of using the provided binaries?

How should I install a raw binary on macOS? Thought SIP protection prevented moving binaries to /usr/bin

**Comment by avdv** [comment]
> Is this a requirement for scalals to build or just an OS recommendation?

Neither. It is not a build requirement, as you can build scalals without it, but then you're on your own to ensure every tool is at the correct version.

And it is not an OS recommendation (yes, there is *NixOS*, which is a Linux distribution I am using but I was talking about *Nix*) rather a way of describing build environments and for reproducible builds. Which is exactly the problem here, since you used a too recent Java version where they changed the API of some classes, the code does not compile anymore. But with ensuring every piece of software inside the build environment (bash, java, sbt, coreutils et cetera) is at the same exact version *everywhere* the project will also build everywhere.



> How should I install a raw binary on macOS? Thought SIP protection prevented moving binaries to /usr/bin

I dont know what SIP protection is, but why would you want to move the binary to `/usr/bin`?

**Comment by alechp** [comment]
* usr/bin --> Good question. Moved to usr/local/bin and worked as expected

* SIP --> https://support.apple.com/en-us/HT204899

* Unfortunately, still didn't replicate colorls behavior
> ![Screen Shot 2020-11-09 at 5 57 56 AM](https://user-images.githubusercontent.com/3058939/99192538-37023a00-2728-11eb-82e2-e71b7dcff6c1.png)

Closing this issue. Ended up moving onto exa instead

**Comment by avdv** [comment]
>     * Unfortunately, still didn't replicate colorls behavior

You mean the colors? That's true, currently you have to set up dircolors via `LS_COLORS` -- I should probably provide some defaults.

Thanks for the feedback!
